services:
  - type: web
    name: owncast
    env: docker
    repo: https://github.com/owncast/owncast
    dockerfilePath: Dockerfile
    plan: free
    autoDeploy: true
    envVars:
      - key: OWNCAST_DATABASE_PATH
        value: /app/data
    healthCheckPath: /
